name = "LineagesMakie"
uuid = "442c8a50-53a9-4dd6-b3a1-02ab81198c2d"
version = "0.1.0"
authors = ["Jeet Sukumaran <jeetsukumaran@gmail.com>"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
AbstractTrees = "0.4.5"
Makie = "0.24"
julia = "1.11"
